### ISSUE TITLE
Running bot

### ISSUE THREAD

**Issue by mkubx** [GarrettFleischer/PoloniexTradingBot#2]
Hello, I really appreciate sharing your code in public. Until the revision `3c51e5000b0b60742de135d9f36a4c0744f57f2b` I was able to use the bot. Just after you made the changes with data sources, when I specify in config file some currency pair, the bot quits right after:

```
initializing


gathering source for BTC_MAID
updating BTC_MAID
initial balances:             $0.00                     4.9875
final balances:               $0.00                     9.9875
difference:                  $-0.00                     5.000000000000001
total moved:                  $0.01                     45.0
accuracy: 100.00%
fees: $0.00
profit $0.00


total profit: $0.00
```

Should I specify something else in the config file besides api keys and currency pairs or in `tradebot.py` to keep the bot running?

**Comment by GarrettFleischer** [comment]
Oh, I've been implementing some backtesting to test various strategies. That is the output of the backtest. 
The latest commit fixed a bunch of things and allowed it to buy and sell on the exchange again. See the updated readme for the review of the changes.

I should have setup dev and test branches, but I didn't realize that other people besides myself were using it haha.
